version: "3"

services:
  yii2_app_loc:
    build: 
      context: provision/nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    restart: unless-stopped
    links:
      - php_yii2_app
    volumes:
      - ./hosts/yii2-app.loc/httpdocs:/app:rw
      - ./hosts/yii2-app.loc/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      VIRTUAL_HOST: yii2-app.loc,back.yii2-app.loc
      VIRTUAL_PORT: 80
    expose:
      - '80'
    dns:
      - ${NETWORK_PROXY_IP}
  php_yii2_app:
    build: provision/php/7.2
    restart: unless-stopped
    links:
      - mysql_yii2_app
    ports:
      - '9012:9000'
    expose:
      - '9000'
      - '9001'
    dns:
      - ${NETWORK_PROXY_IP}
    environment:
      - PHP_IDE_CONFIG=serverName=yii2-app.loc
    volumes:
      - ./hosts/yii2-app.loc/httpdocs:/app:rw
  mysql_yii2_app:
    build: provision/mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yii2-app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3315:3306'
    dns:
      - ${NETWORK_PROXY_IP}
    volumes:
      - './scripts:/app'

networks:
    default:
       external:
         name: '${NETWORK}'