version: "3"

services:
  yii3_demo_loc:
    build: 
      context: provision/nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    container_name: yii3-demo.loc
    restart: unless-stopped
    links:
      - php_yii3_demo
    volumes:
      - ./hosts/yii3-demo.loc/httpdocs:/demo:rw
      - ./hosts/yii3-demo.loc/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      VIRTUAL_HOST: yii3-demo.loc
      VIRTUAL_PORT: 80
    expose:
      - '80'
    dns:
      - ${NETWORK_PROXY_IP}
  php_yii3_demo:
    build: provision/php/7.4
    container_name: php_yii3_demo
    restart: unless-stopped
    links:
      - mysql_yii3_demo
    ports:
      - '9004:9000'
    expose:
      - '9000'
      - '9001'
    dns:
      - ${NETWORK_PROXY_IP}
    environment:
      - PHP_IDE_CONFIG=serverName=yii3-demo.loc
    volumes:
      - ./hosts/yii3-demo.loc/httpdocs:/demo:rw
  mysql_yii3_demo:
    build: provision/mariadb
    container_name: mysql_yii3_demo
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yii3-demo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3309:3306'
    dns:
      - ${NETWORK_PROXY_IP}
    volumes:
      - './scripts:/demo'

networks:
  default:
    external:
      name: '${NETWORK}'